=# render.yaml
services:
  - type: web
    name: explore-md-v4
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    # Auto-deploy from GitHub
    autoDeploy: true